// 模版
export const formTemplates = [
  {
    title: '单列表单json',
    imgUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/t1.png',
    // jsonUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/json1.txt',
    description: '表单模板详细说明...',
    jsonStr: '{"widgetList":[{"type":"static-text","icon":"static-text","formItemFlag":false,"options":{"name":"statictext111193","columnWidth":"200px","hidden":false,"textContent":"单列表单","customClass":[],"onCreated":"","onMounted":"","label":"static-text"},"id":"statictext111193"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider102346","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider102346"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input12931","label":"发件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input12931"},{"type":"switch","icon":"switch-field","formItemFlag":true,"options":{"name":"switch96070","label":"是否保密","labelAlign":"","defaultValue":true,"columnWidth":"200px","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"switchWidth":40,"activeText":"","inactiveText":"","activeColor":null,"inactiveColor":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"switch96070"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input23031","label":"发件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input23031"},{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea21654","label":"发件人地址","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea21654"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider69240","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":"","onCreated":"","onMounted":""},"id":"divider69240"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input113152","label":"收件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input113152"},{"type":"checkbox","icon":"checkbox-field","formItemFlag":true,"options":{"name":"checkbox63174","label":"接收时间段","labelAlign":"","defaultValue":[],"columnWidth":"200px","size":"","displayStyle":"inline","buttonStyle":false,"border":false,"labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"optionItems":[{"label":"上午9:00 - 11:30","value":1},{"label":"下午12:30 - 18:00","value":2},{"label":"晚上18:00 - 21:00","value":3}],"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"checkbox63174"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input40240","label":"收件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input40240"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input78584","label":"收件人地址","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input78584"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider75887","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider75887"},{"type":"time-range","icon":"time-range-field","formItemFlag":true,"options":{"name":"timerange47503","label":"送货时间","labelAlign":"","defaultValue":null,"startPlaceholder":"","endPlaceholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"editable":false,"format":"HH:mm:ss","required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"timerange47503"},{"type":"slider","icon":"slider-field","formItemFlag":true,"options":{"name":"slider54714","label":"价格保护","labelAlign":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"min":0,"max":100,"step":10,"range":false,"height":null,"onCreated":"","onMounted":"","onChange":"","onValidate":"","showStops":true},"id":"slider54714"},{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea64794","label":"其他信息","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea64794"}],"formConfig":{"modelName":"formData","refName":"vForm","rulesName":"rules","labelWidth":150,"labelPosition":"left","size":"","labelAlign":"label-right-align","cssCode":"","customClass":[],"functions":"","layoutType":"PC","jsonVersion":3,"onFormCreated":"","onFormMounted":"","onFormDataChange":""}}'
  },

  {
    title: '多列表单',
    imgUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/t2.png',
    // jsonUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/json2.txt',
    description: '表单模板详细说明...',
    jsonStr: '{"widgetList":[{"type":"static-text","icon":"static-text","formItemFlag":false,"options":{"name":"statictext111193","columnWidth":"200px","hidden":false,"textContent":"å¤šåˆ—è¡¨å\x8D•","customClass":[],"onCreated":"","onMounted":"","label":"static-text"},"id":"statictext111193"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider102346","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider102346"},{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input12931","label":"å\x8F‘ä»¶äººå§“å\x90\x8D","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input12931"}],"options":{"name":"gridCol25469","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":[]},"id":"grid-col-25469"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input23031","label":"å\x8F‘ä»¶äººå\x8F·ç \x81","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input23031"}],"options":{"name":"gridCol25125","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-25125"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"switch","icon":"switch-field","formItemFlag":true,"options":{"name":"switch96070","label":"æ˜¯å\x90¦ä¿\x9Då¯†","labelAlign":"","defaultValue":true,"columnWidth":"200px","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"switchWidth":40,"activeText":"","inactiveText":"","activeColor":null,"inactiveColor":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"switch96070"}],"options":{"name":"gridCol44470","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-44470"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea21654","label":"å\x8F‘ä»¶äººåœ°å\x9D€","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea21654"}],"options":{"name":"gridCol98223","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-98223"}],"options":{"name":"grid35834","hidden":false,"gutter":12,"customClass":""},"id":"grid35834"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider69240","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":"","onCreated":"","onMounted":""},"id":"divider69240"},{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input113152","label":"æ”¶ä»¶äººå§“å\x90\x8D","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input113152"}],"options":{"name":"gridCol47242","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-47242"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input40240","label":"æ”¶ä»¶äººå\x8F·ç \x81","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input40240"}],"options":{"name":"gridCol27970","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-27970"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"checkbox","icon":"checkbox-field","formItemFlag":true,"options":{"name":"checkbox63174","label":"æŽ¥æ”¶æ—¶é—´æ®µ","labelAlign":"","defaultValue":[],"columnWidth":"200px","size":"","displayStyle":"inline","buttonStyle":false,"border":false,"labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"optionItems":[{"label":"ä¸Šå\x8Dˆ9:00 - 11:30","value":1},{"label":"ä¸‹å\x8Dˆ12:30 - 18:00","value":2},{"label":"æ™šä¸Š18:00 - 21:00","value":3}],"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"checkbox63174"}],"options":{"name":"gridCol74653","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-74653"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input78584","label":"æ”¶ä»¶äººåœ°å\x9D€","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input78584"}],"options":{"name":"gridCol63781","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-63781"}],"options":{"name":"grid114672","hidden":false,"gutter":12,"customClass":""},"id":"grid114672"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider75887","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider75887"},{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"time-range","icon":"time-range-field","formItemFlag":true,"options":{"name":"timerange47503","label":"é€\x81è´§æ—¶é—´","labelAlign":"","defaultValue":null,"startPlaceholder":"","endPlaceholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"editable":false,"format":"HH:mm:ss","required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"timerange47503"}],"options":{"name":"gridCol109912","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-109912"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"slider","icon":"slider-field","formItemFlag":true,"options":{"name":"slider54714","label":"ä»·æ ¼ä¿\x9DæŠ¤","labelAlign":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"min":0,"max":100,"step":10,"range":false,"height":null,"onCreated":"","onMounted":"","onChange":"","onValidate":"","showStops":true},"id":"slider54714"}],"options":{"name":"gridCol114653","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-114653"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea64794","label":"å…¶ä»–ä¿¡æ\x81¯","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea64794"}],"options":{"name":"gridCol80867","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-80867"}],"options":{"name":"grid28709","hidden":false,"gutter":12,"customClass":""},"id":"grid28709"}],"formConfig":{"modelName":"formData","refName":"vForm","rulesName":"rules","labelWidth":150,"labelPosition":"left","size":"","labelAlign":"label-right-align","cssCode":"","customClass":[],"functions":"","layoutType":"PC","onFormCreated":"","onFormMounted":"","onFormDataChange":"","onFormValidate":""}}'
  },

  {
    title: '分组表单',
    imgUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/t3.png',
    // jsonUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/json3.txt',
    description: '表单模板详细说明...',
    jsonStr:'{"widgetList":[{"type":"static-text","icon":"static-text","formItemFlag":false,"options":{"name":"statictext111193","columnWidth":"200px","hidden":false,"textContent":"分组表单","customClass":[],"onCreated":"","onMounted":"","label":"static-text"},"id":"statictext111193"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider102346","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":true,"customClass":[],"onCreated":"","onMounted":""},"id":"divider102346"},{"type":"card","category":"container","icon":"card","widgetList":[{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input12931","label":"发件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input12931"}],"options":{"name":"gridCol25469","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-25469"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input23031","label":"发件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input23031"}],"options":{"name":"gridCol25125","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-25125"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"switch","icon":"switch-field","formItemFlag":true,"options":{"name":"switch96070","label":"是否保密","labelAlign":"","defaultValue":true,"columnWidth":"200px","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"switchWidth":40,"activeText":"","inactiveText":"","activeColor":null,"inactiveColor":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"switch96070"}],"options":{"name":"gridCol38707","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-38707"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea21654","label":"发件人地址","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea21654"}],"options":{"name":"gridCol36174","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-36174"}],"options":{"name":"grid35834","hidden":false,"gutter":12,"customClass":""},"id":"grid35834"}],"options":{"name":"card27350","label":"发件信息","hidden":false,"folded":false,"showFold":true,"cardWidth":"100%","shadow":"never","customClass":""},"id":"card27350"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider69240","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":true,"customClass":"","onCreated":"","onMounted":""},"id":"divider69240"},{"type":"card","category":"container","icon":"card","widgetList":[{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input113152","label":"收件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input113152"}],"options":{"name":"gridCol47242","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-47242"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input40240","label":"收件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input40240"}],"options":{"name":"gridCol27970","hidden":false,"span":12,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-27970"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"checkbox","icon":"checkbox-field","formItemFlag":true,"options":{"name":"checkbox63174","label":"接收时间段","labelAlign":"","defaultValue":[],"columnWidth":"200px","size":"","displayStyle":"inline","buttonStyle":false,"border":false,"labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"optionItems":[{"label":"上午9:00 - 11:30","value":1},{"label":"下午12:30 - 18:00","value":2},{"label":"晚上18:00 - 21:00","value":3}],"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"checkbox63174"}],"options":{"name":"gridCol93630","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-93630"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input78584","label":"收件人地址","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input78584"}],"options":{"name":"gridCol65188","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-65188"}],"options":{"name":"grid114672","hidden":false,"gutter":12,"customClass":""},"id":"grid114672"}],"options":{"name":"card111229","label":"收件信息","hidden":false,"folded":false,"showFold":true,"cardWidth":"100%","shadow":"never","customClass":""},"id":"card111229"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider75887","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":true,"customClass":[],"onCreated":"","onMounted":""},"id":"divider75887"},{"type":"card","category":"container","icon":"card","widgetList":[{"type":"grid","category":"container","icon":"grid","cols":[{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"time-range","icon":"time-range-field","formItemFlag":true,"options":{"name":"timerange47503","label":"送货时间","labelAlign":"","defaultValue":null,"startPlaceholder":"","endPlaceholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"editable":false,"format":"HH:mm:ss","required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"timerange47503"}],"options":{"name":"gridCol109912","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-109912"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"slider","icon":"slider-field","formItemFlag":true,"options":{"name":"slider54714","label":"价格保护","labelAlign":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"min":0,"max":100,"step":10,"range":false,"height":null,"onCreated":"","onMounted":"","onChange":"","onValidate":"","showStops":true},"id":"slider54714"}],"options":{"name":"gridCol114653","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-114653"},{"type":"grid-col","category":"container","icon":"grid-col","internal":true,"widgetList":[{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea64794","label":"其他信息","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea64794"}],"options":{"name":"gridCol80867","hidden":false,"span":24,"offset":0,"push":0,"pull":0,"responsive":false,"md":12,"sm":12,"xs":12,"customClass":""},"id":"grid-col-80867"}],"options":{"name":"grid28709","hidden":false,"gutter":12,"customClass":""},"id":"grid28709"}],"options":{"name":"card106066","label":"补充信息","hidden":false,"folded":false,"showFold":true,"cardWidth":"100%","shadow":"never","customClass":""},"id":"card106066"}],"formConfig":{"modelName":"formData","refName":"vForm","rulesName":"rules","labelWidth":150,"labelPosition":"left","size":"","labelAlign":"label-right-align","cssCode":"","customClass":[],"functions":"","layoutType":"PC","jsonVersion":3,"onFormCreated":"","onFormMounted":"","onFormDataChange":"","onFormValidate":""}}'
  },

  {
    title: '标签页表单',
    imgUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/t4.png',
    // jsonUrl: 'https://ks3-cn-beijing.ksyuncs.com/vform-static/form-samples/json4.txt',
    description: '表单模板详细说明...',
    jsonStr: '{"widgetList":[{"type":"static-text","icon":"static-text","formItemFlag":false,"options":{"name":"statictext111193","columnWidth":"200px","hidden":false,"textContent":"标签页表单","customClass":[],"onCreated":"","onMounted":"","label":"static-text"},"id":"statictext111193"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider102346","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider102346"},{"type":"tab","category":"container","icon":"tab","displayType":"border-card","tabs":[{"type":"tab-pane","category":"container","icon":"tab-pane","internal":true,"widgetList":[{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input12931","label":"发件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input12931"},{"type":"switch","icon":"switch-field","formItemFlag":true,"options":{"name":"switch96070","label":"是否保密","labelAlign":"","defaultValue":true,"columnWidth":"200px","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"switchWidth":40,"activeText":"","inactiveText":"","activeColor":null,"inactiveColor":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"switch96070"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input23031","label":"发件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input23031"},{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea21654","label":"发件人地址","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea21654"},{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider69240","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider69240"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input113152","label":"收件人姓名","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input113152"},{"type":"checkbox","icon":"checkbox-field","formItemFlag":true,"options":{"name":"checkbox63174","label":"接收时间段","labelAlign":"","defaultValue":[],"columnWidth":"200px","size":"","displayStyle":"inline","buttonStyle":false,"border":false,"labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"optionItems":[{"label":"上午9:00 - 11:30","value":1},{"label":"下午12:30 - 18:00","value":2},{"label":"晚上18:00 - 21:00","value":3}],"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onValidate":""},"id":"checkbox63174"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input40240","label":"收件人号码","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input40240"},{"type":"input","icon":"text-field","formItemFlag":true,"options":{"name":"input78584","label":"收件人地址","labelAlign":"","type":"text","defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"showPassword":false,"required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"prefixIcon":"","suffixIcon":"","appendButton":false,"appendButtonDisabled":false,"buttonIcon":"el-icon-search","onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"input78584"}],"options":{"name":"tab1","label":"发件&收件信息","hidden":false,"active":true,"disabled":false,"customClass":""},"id":"tab-pane-70250"},{"type":"tab-pane","category":"container","icon":"tab-pane","internal":true,"widgetList":[{"type":"divider","icon":"divider","formItemFlag":false,"options":{"name":"divider75887","label":"","columnWidth":"200px","direction":"horizontal","contentPosition":"center","hidden":false,"customClass":[],"onCreated":"","onMounted":""},"id":"divider75887"},{"type":"time-range","icon":"time-range-field","formItemFlag":true,"options":{"name":"timerange47503","label":"送货时间","labelAlign":"","defaultValue":null,"startPlaceholder":"","endPlaceholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"clearable":true,"editable":false,"format":"HH:mm:ss","required":true,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"onCreated":"","onMounted":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"timerange47503"},{"type":"slider","icon":"slider-field","formItemFlag":true,"options":{"name":"slider54714","label":"价格保护","labelAlign":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":[],"labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"min":0,"max":100,"step":10,"range":false,"height":null,"onCreated":"","onMounted":"","onChange":"","onValidate":"","showStops":true},"id":"slider54714"},{"type":"textarea","icon":"textarea-field","formItemFlag":true,"options":{"name":"textarea64794","label":"其他信息","labelAlign":"","rows":3,"defaultValue":"","placeholder":"","columnWidth":"200px","size":"","labelWidth":null,"labelHidden":false,"readonly":false,"disabled":false,"hidden":false,"required":false,"validation":"","validationHint":"","customClass":"","labelIconClass":null,"labelIconPosition":"rear","labelTooltip":null,"minLength":null,"maxLength":null,"showWordLimit":false,"onCreated":"","onMounted":"","onInput":"","onChange":"","onFocus":"","onBlur":"","onValidate":""},"id":"textarea64794"}],"options":{"name":"tab-pane-48281","label":"补充信息","hidden":false,"active":false,"disabled":false,"customClass":""},"id":"tab-pane-48281"}],"options":{"name":"tab60554","hidden":false,"customClass":[]},"id":"tab60554"}],"formConfig":{"modelName":"formData","refName":"vForm","rulesName":"rules","labelWidth":150,"labelPosition":"left","size":"","labelAlign":"label-right-align","cssCode":"","customClass":[],"functions":"","layoutType":"PC","jsonVersion":3,"onFormCreated":"","onFormMounted":"","onFormDataChange":"","onFormValidate":""}}'
  }
]

export const fieldList = [
  {
      // 是否必填
      "notNull": 1,
      // 名称
      "displayName": "id",
      // 描述
      "description": "唯一标识ID;主键",
      // 长度
      "scale": 36,
      // 
      "id": "07c2d08e-9168-40be-9e34-0b63fcaaf172",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "type": "VARCHAR",
      "precisions": null,
      "primaryKey": 1,
      "systemField": 1,
      "fieldOrder": 1,
      "whereType": "",
      "hasWhere": 0,
      "display": 0
  },
  {
      "id": "0af1d1e7-c054-4604-b62b-27df48369771",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "creatorId",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 36,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "创建人ID",
      "fieldOrder": 2,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "97563e3c-bc95-4b43-a556-44675c5cc046",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "creatorBy",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 32,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "创建人",
      "fieldOrder": 3,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "4b6637f9-aebc-4ee2-bbc6-d82ce071865a",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "createTime",
      "type": "DATETIME",
      "precisions": null,
      "scale": 6,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "创建时间",
      "fieldOrder": 4,
      "whereType": "like",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "33294edc-0805-46a3-8902-9551954acada",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "modifyId",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 36,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "修改者id",
      "fieldOrder": 5,
      "whereType": "like",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "38e043d9-f7a2-445d-b65a-9bd6f3af6dc2",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "modifyBy",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 32,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "修改者",
      "fieldOrder": 6,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "c5864a09-d7ff-4e3c-b56f-7d2512e0fc06",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "modifyTime",
      "type": "DATETIME",
      "precisions": null,
      "scale": 6,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "更新时间",
      "fieldOrder": 7,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "8c8eccf5-dedd-477d-a733-1f8b3ba9c034",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "name",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "客户名称",
      "fieldOrder": 8,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "0d231a12-635b-46ca-8a0d-d5b4b8228e4e",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "classType",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "客户类型",
      "fieldOrder": 9,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "2fcd5e65-0343-46b2-bf95-1e88d357d1d9",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "source",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "客户来源",
      "fieldOrder": 10,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "a32cbe87-4024-4f17-a2d0-c65270b607cb",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "label",
      "type": "TEXT",
      "precisions": null,
      "scale": null,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "客户标签",
      "fieldOrder": 11,
      "whereType": "in",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "0116932f-f198-4dc2-97b8-d1ef22265fce",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "sex",
      "type": "CHAR",
      "precisions": null,
      "scale": 1,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "性别",
      "fieldOrder": 12,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "b7c5d9bd-175a-4da3-af4c-b92e8db2bfeb",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "qq",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "QQ",
      "fieldOrder": 13,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "dabce0ac-1c6c-4614-936c-16c492859406",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "province",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "省",
      "fieldOrder": 14,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "3bea313f-be47-46c9-86a6-612ca86ed63e",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "city",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "市",
      "fieldOrder": 15,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "e59e0012-3670-468e-9a2e-6c898e26eed4",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "area",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "区",
      "fieldOrder": 16,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "36a545a1-5a71-446f-8f7d-db6213fe3c64",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "birthday",
      "type": "DATE",
      "precisions": null,
      "scale": null,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "出生日期",
      "fieldOrder": 17,
      "whereType": "between",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "6d408f7e-3091-430e-ae01-e3da2557b37d",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "phone",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 1,
      "primaryKey": 0,
      "systemField": 1,
      "description": "联系电话",
      "fieldOrder": 18,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "780a40ee-8c4f-4d33-8927-e22db8910989",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "phoneTwo",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "联系电话2",
      "fieldOrder": 19,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "e6adac73-c1e9-421f-8c9c-a19b6295dcfa",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "tel",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "固定电话",
      "fieldOrder": 20,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "82a27a52-ce65-416d-97db-a786b2caa0ba",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "email",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "电子邮箱",
      "fieldOrder": 21,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "f34d93ca-17b1-4317-acb1-085e04ad6731",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "address",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "通讯地址",
      "fieldOrder": 22,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "40827ea4-d623-44ec-935f-c5685ce2ad01",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "memo",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "备注",
      "fieldOrder": 23,
      "whereType": "like",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "dd2e6d7a-8be5-4e3c-9547-0ebfef7529c6",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "isContactPlan",
      "type": "TINYINT",
      "precisions": null,
      "scale": 32,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "是否有联系计划",
      "fieldOrder": 25,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 1
  },
  {
      "id": "32fe6c91-ca7c-4e9c-8b39-3492cb2398c5",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "poolId",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 36,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "公海Id",
      "fieldOrder": 26,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "3d1d948b-419f-45f0-aae3-61760eaf73da",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "receiveTime",
      "type": "DATETIME",
      "precisions": null,
      "scale": null,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "公海领取时间",
      "fieldOrder": 27,
      "whereType": "between",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "3169db25-3bef-4e56-90d3-f616664ec84d",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "ownerName",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 255,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "所属人姓名",
      "fieldOrder": 28,
      "whereType": "like",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "778a7e97-139e-4af1-b040-c6dfdcfccfa2",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "ownerId",
      "type": "VARCHAR",
      "precisions": null,
      "scale": 36,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "所属人ID",
      "fieldOrder": 29,
      "whereType": "eq",
      "hasWhere": 1,
      "display": 0
  },
  {
      "id": "e0f31895-3b8e-42c1-bd82-36a3271dc4a6",
      "tenantId": "0000000B",
      "tableId": "82210797-c527-4797-9fc3-48d35849ecfc",
      "displayName": "labelName",
      "type": "TEXT",
      "precisions": null,
      "scale": null,
      "notNull": 0,
      "primaryKey": 0,
      "systemField": 1,
      "description": "标签名",
      "fieldOrder": 30,
      "whereType": "like",
      "hasWhere": 1,
      "display": 1
  }
]

export const optionsDict = [
  {
    id: 'customerType',
    label: '客户类型',
    options: [
      {
        label: 'vip客户',
        value: '1'
      },
      {
        label: '普通客户',
        value: '2'
      },
      {
        label: '劣质客户',
        value: '3'
      },
    ]
  },
  {
    id: 'customerSource',
    label: '客户来源',
    options: [
      {
        label: '网站',
        value: '1'
      },
      {
        label: '小广告',
        value: '2'
      },
      {
        label: '听别人说的',
        value: '3'
      },
    ]
  },
  {
    id: 'workOrderType',
    label: '工单类型',
    options: [
      {
        label: '大工单',
        value: '1'
      },
      {
        label: '小工单',
        value: '2'
      },
      {
        label: '打工单',
        value: '3'
      },
    ]
  },
]